### ISSUE TITLE
Allgemeine Diskussion

### ISSUE THREAD

**Issue by Bergmaier** [sweIhm-ws2018-19/skillproject-fr-33#17]
@Angiabc wrote
> Bis Freitag, 23.11. (unser nächstes Treffen) brauchen wir einen mehr oder weniger funktionierenden Prototypen. D.h. eine Person sollte sich orten lassen können, ein Quiz zu einer Stadt spielen können und sich danach den Punktestand durchsagen lassen können.
> 
> Wäre super, wenn Ihr den Kommunikationsfluss in Getstoryline mal durchspielen würdet (geht nur in Chrome) und ggf. Bescheid gebt (bis Dienstag, 13.11.), wenn es Rückfragen gibt.

**Comment by Bergmaier** [comment]
Hallo,
mal sehen was sich machen lässt um einen Prototypen zu erstellen. GPS können wir noch nicht versprechen, aber ein Quiz einmal durchspielen können (mit ein paar festverdrahteten Fragen) sollte zu schaffen sein.

Erstmal müssen wir bis nächsten Donnerstag den "Sprint 0" abschließen (die erste Moodle-Aufgabe), und würden Euch dazu bitten auch ein paar "User Stories" (googelt das mal) zu verfassen ([Punkt 6 b](https://moodle.hm.edu/mod/assign/view.php?id=347977)). Die müssen nicht perfekt sein, sondern erstmal nur viele - von jedem ein paar, damit wir die Wünsche und Vorstellungen von jedem Teammitglied sehen. Wie die dann präzisiert werden und welche davon zuerst implementiert werden wird am Freitag (16. 11.) vom Entwicklungsteam festgelegt.

**Comment by Bergmaier** [comment]
Mein persönlicher Senf zum Getstoryline-Prototypen:
* Soll der Skill wirklich jede Äußerung mit "Wahnsinn!", "Super!", "Spitze!", "Toll!" etc. beginnen? Ich weiß nicht ob das auf Dauer nicht nervt. Vermutlich sollte das auch zufällig sein, damit es sich ständige Wiederholung nicht so monoton anfühlt?
* Das ist ganz schön viel Sprachausgabe am Anfang, bevor es wirklich los geht. Sollten man das ein wenig abkürzen können, indem man den Skill startet mit "Alexa, ich möchte ein Reisequiz spielen mit 3 Spielern auf dem Weg von hier nach Genf"?
* Ähnlich zwischen den Quizzes: "*Weiter geht's mit der zweiten Runde. Willst du weitere Fragen zur selben Region oder eine neue Destination auswählen?*" - "*Neue Destination*" - "*Ok. Die nächste Region auf deiner Route ist Garmisch. Möchtest du darüber ein Quiz spielen?*" - "*Ja*". Stattdessen würde ich mir wünschen, dass Alexa einfach "*Weiter geht's mit der zweiten Runde, zur nächsten Region auf deiner Route: Garmisch. Welche ...*" sagt. Dann kann man immer noch abbrechen mit "*Halt, nochmal eine Runde zur vorherigen Region spielen*" oder "*Frag uns lieber etwas zum Thema Berlin*".

**Comment by Bergmaier** [comment]
Btw @Angiabc @Claraabc @rena611 habt ihr das Repository auf eurer [Watchlist](https://help.github.com/articles/watching-and-unwatching-repositories/#watching-a-single-repository) stehen, sodass ihr bei allen Änderungen eine Email bekommt?

**Comment by Claraabc** [comment]
Hey ja wir kriegen Benachrichtigung, danke für die schnellen Antworten 😊 Das mit den user storys machen wir bis Donnerstag. 
- Dann das mit wahnsinnig, super, usw. war eben wie du schon gesagt hast so gemeint, dass wir ganz viele Synonyme nehmen und die dann zufällig genommen werden. Das selbe dann entsprechend für falsche Antworten.
- Das am Anfang kann man Abkürzung. Wir wollten halt die Möglichkeit, dass man anstatt über GPS auch über eine beliebige Stadt spielen kann. Drum ist das so lang geworden. Finde deinen Vorschlag schon gut, allerdings sollte die Anwendung für alle verwendbar sein, die das Spiel noch nicht kennen. Deswegen haben wir die ganzen Abfragen von Alexa rein...
- Dein letzter Vorschlag ist super! Wir fanden das auch so lang aber dachten nicht, dass Alexa dann nochmal zurück kann, wenn sie schon gesagt hat es geht mit der zweiten Runde weiter. Aber wenn das geht wär's sogar besser weil's eben wie du gesagt hast dann nicht so lang ist.

**Comment by rena611** [comment]
Hey hey,
ich melde mich jetzt auch mal:). Bezüglich der User Stories haben wir jetzt nochmal von unserem Prof gesagt bekommen, dass das in euer Aufgabengebiet fällt. Wir können dann gerne darüber schauen oder helfen, wenn Fragen anfallen.
Wir würden vorschlagen uns diesen Freitag, 16.11. um 13:30 Uhr zu treffen.Dann können wir alles noch mal durch sprechen. Passt das für euch?

**Comment by Bergmaier** [comment]
Hallo,
wir sind am Freitag auf alle Fälle da :-) Viel Zeit zum Besprechen der [User stories](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues?utf8=✓&q=label%3A"user+story") haben wir aber nicht, vielleicht eine halbe bis dreiviertel Stunde? Das Development-Team muss danach noch [den ersten Sprint planen](https://moodle.hm.edu/mod/assign/view.php?id=349666). Es wäre gut wenn ihr schonmal die User stories durchschauen könntet und kommentieren wenn etwas nicht passt oder fehlt.

**Comment by Angiabc** [comment]
Okay super! Die User Stories passen (meines Erachtens) so :) Es ginge dann am Freitag eher darum, mal den aktuellen Stand zu besprechen und auch abzuklären, was unsere weiteren To Dos sind.
Ihr seid ab 13:30 da oder?

**Comment by Bergmaier** [comment]
Ja, wir sind seit 13:30 da (Raum R2.014). Wo seid ihr?

**Comment by Angiabc** [comment]
Achso hm, wir haben von der Frau Socher durch unseren Prof die Anweisung bekommen, uns heute nicht mit euch zu treffen, damit ihr Zeit zum programmieren habt.. Dachten, sie hätte das euch auch kommuniziert .. Hoffe ihr habt jetzt nicht umsonst gewartet !

**Comment by Bergmaier** [comment]
Kurze Wasserstandsmeldung: habe heute erfolgreich meine eigene Lambda-Funktion eingerichtet (und den Endpoint unseres gemeinsamen Skills dorthin umgebogen). Bin allerdings mit der Implementierung der Runde noch nicht fertig geworden.

**Comment by Bergmaier** [comment]
Terminvorschläge:
(Andreas, Fabian, Naomi, Clara, Angie, Verena)
* :heavy_check_mark: :heavy_check_mark: :white_circle: :heavy_check_mark: :heavy_check_mark:  :heavy_check_mark: Mo 17:00
* :heavy_check_mark: :white_circle: :white_circle: :heavy_check_mark: :heavy_check_mark: :heavy_check_mark: Di 11:30-11:45
* :x: :white_circle: :white_circle: :heavy_check_mark: :x: :heavy_check_mark: Mi 10:00
* :heavy_check_mark: :white_circle: :x: :heavy_check_mark: :x: :heavy_check_mark: Mi 15:30
* :heavy_check_mark: :white_circle: :white_circle: :x: :x: :heavy_check_mark: Do 17:00

**Comment by Angiabc** [comment]
✔️ ✔️ ⚪️ ⚪️ ✔️⚪️ Mo 17:00
✔️ ⚪️ ⚪️ ⚪️ ✔️ ⚪️ Di 11:30-11:45
✔️ ⚪️ ⚪️ ⚪️ ❌ ⚪️ Mi 10:00
✔️ ⚪️ ❌ ⚪️ ❌ ⚪️ Mi 15:30
✔️ ⚪️ ⚪️ ⚪️ ❌ ⚪️ Do 17:00

**Comment by Bergmaier** [comment]
@fft5woosh @Ruleya Lieber heute nachmittag oder morgen vormittag?

**Comment by rena611** [comment]
Uns wäre morgen Vormittag lieber, wenn dafür euch auch passt? :)

**Comment by Ruleya** [comment]
bist du noch da? Bin bei 2.012
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 03.12.18, 08:43, Bergmaier <notifications@github.com> schrieb:
@fft5woosh @Ruleya Lieber heute nachmittag oder morgen vormittag?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sweIhm-ws2018-19/skillproject-fr-33","title":"sweIhm-ws2018-19/skillproject-fr-33","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sweIhm-ws2018-19/skillproject-fr-33"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Bergmaier in #17: @fft5woosh @Ruleya Lieber heute nachmittag oder morgen vormittag?"}],"action":{"name":"View Issue","url":"https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443616706"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443616706",
"url": "https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443616706",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [sweIhm-ws2018-19/skillproject-fr-33] Allgemeine Diskussion (#17)",
"sections": [
{
"text": "",
"activityTitle": "**Bergmaier**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Bergmaier",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"sweIhm-ws2018-19/skillproject-fr-33\",\n\"issueId\": 17,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"sweIhm-ws2018-19/skillproject-fr-33\",\n\"issueId\": 17\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443616706"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 408580807\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Angiabc** [comment]
Also morgen um 11:30?

**Comment by Bergmaier** [comment]
Ja, 11:30 im üblichen Korridor.

**Comment by Ruleya** [comment]
schaffs nicht mehr rechtzeitig ._. komm wahrscheinlich etwas spät
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 03.12.18, 23:21, Bergmaier <notifications@github.com> schrieb:
Ja, 11:30 im üblichen Korridor.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sweIhm-ws2018-19/skillproject-fr-33","title":"sweIhm-ws2018-19/skillproject-fr-33","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sweIhm-ws2018-19/skillproject-fr-33"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Bergmaier in #17: Ja, 11:30 im üblichen Korridor."}],"action":{"name":"View Issue","url":"https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443893021"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443893021",

"url": "https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443893021",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

},

{

"@type": "MessageCard",

"@context": "http://schema.org/extensions",

"hideOriginalBody": "false",

"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",

"title": "Re: [sweIhm-ws2018-19/skillproject-fr-33] Allgemeine Diskussion (#17)",

"sections": [

{

"text": "",

"activityTitle": "**Bergmaier**",

"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",

"activitySubtitle": "@Bergmaier",

"facts": [



]

}

],

"potentialAction": [

{

"name": "Add a comment",

"@type": "ActionCard",

"inputs": [

{

"isMultiLine": true,

"@type": "TextInput",

"id": "IssueComment",

"isRequired": false

}

],

"actions": [

{

"name": "Comment",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"sweIhm-ws2018-19/skillproject-fr-33\",\n\"issueId\": 17,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"

}

]

},

{

"name": "Close issue",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"sweIhm-ws2018-19/skillproject-fr-33\",\n\"issueId\": 17\n}"

},

{

"targets": [

{

"os": "default",

"uri": "https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443893021"

}

],

"@type": "OpenUri",

"name": "View on GitHub"

},

{

"name": "Unsubscribe",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 408580807\n}"

}

],

"themeColor": "26292E"

}

]

**Comment by Ruleya** [comment]
bist du/sind die Touries noch da?
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 03.12.18, 23:21, Bergmaier <notifications@github.com> schrieb:
Ja, 11:30 im üblichen Korridor.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sweIhm-ws2018-19/skillproject-fr-33","title":"sweIhm-ws2018-19/skillproject-fr-33","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sweIhm-ws2018-19/skillproject-fr-33"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Bergmaier in #17: Ja, 11:30 im üblichen Korridor."}],"action":{"name":"View Issue","url":"https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443893021"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443893021",

"url": "https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443893021",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

},

{

"@type": "MessageCard",

"@context": "http://schema.org/extensions",

"hideOriginalBody": "false",

"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",

"title": "Re: [sweIhm-ws2018-19/skillproject-fr-33] Allgemeine Diskussion (#17)",

"sections": [

{

"text": "",

"activityTitle": "**Bergmaier**",

"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",

"activitySubtitle": "@Bergmaier",

"facts": [



]

}

],

"potentialAction": [

{

"name": "Add a comment",

"@type": "ActionCard",

"inputs": [

{

"isMultiLine": true,

"@type": "TextInput",

"id": "IssueComment",

"isRequired": false

}

],

"actions": [

{

"name": "Comment",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"sweIhm-ws2018-19/skillproject-fr-33\",\n\"issueId\": 17,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"

}

]

},

{

"name": "Close issue",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"sweIhm-ws2018-19/skillproject-fr-33\",\n\"issueId\": 17\n}"

},

{

"targets": [

{

"os": "default",

"uri": "https://github.com/sweIhm-ws2018-19/skillproject-fr-33/issues/17#issuecomment-443893021"

}

],

"@type": "OpenUri",

"name": "View on GitHub"

},

{

"name": "Unsubscribe",

"@type": "HttpPOST",

"target": "https://api.github.com",

"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 408580807\n}"

}

],

"themeColor": "26292E"

}

]

**Comment by Angiabc** [comment]
Ja wir sind noch da :)

**Comment by Angiabc** [comment]
Nächstes Treffen: Montag 10.12 17:00 Schachenmeierstraße 35.
Todos:
- [ ] Issue erstellen mit Text, an welcher Stelle im Spieldialog welche (flexiblen) Äußerungen auftreten.
   Auch Fehlerbehandlung: Was sagt Alexa wenn sie was nicht versteht, wenn falsche region eingegeben wird?
  https://developer.amazon.com/docs/alexa-design/design-voice.html
- [ ] Echo #36 
- [ ] Spielernamen - liste erstellen 
- [ ] Koordinaten für Regionen
- [ ] Antwortmöglichkeiten selbst erkennen

**Comment by Bergmaier** [comment]
Hallo, ich habe mal eine Wiki-Seite für die Äußerungen erstellt: https://github.com/sweIhm-ws2018-19/skillproject-fr-33/wiki/Dialoge
Bitte einfach ändern wenn ihr es peppiger (oder einfach nur anders) haben wollt. Und Fälle hinzufügen (mit "wenn ... dann ... ") wo wir noch gar nichts haben.

**Comment by Bergmaier** [comment]
Auch noch gefunden: https://github.com/KayLerch/alexa-morse-coder/blob/master/skill/src/main/resources/out/de-DE/utterances.yml als Beispiel. Lasst euch inspirieren!

**Comment by rena611** [comment]
Hi,
wir gehen Mittwoch Abend mit unserer Kompetenzfeld Gruppe auf das Tollwood und wollten fragen, ob ihr Lust hättet mit zu kommen. Eventuell sind auch andere Kommilitonen von eurer Fakultät dabei :)

**Comment by Bergmaier** [comment]
Wir verspäten uns 10min, kommen aber noch :-)

**Comment by Bergmaier** [comment]
Für die Präsentation: probiert https://slides.com/ mal aus, die fertige HTML-Seite können wir dann hoffentlich für "Offline-Nutzung" herunterladen und so auf die Github-Seite stellen.

**Comment by Bergmaier** [comment]
Hallo,
lauf Fr. Socher müsst ihr euch auf developer.amazon.com anmelden, dann zu der [Skill-Konsole](https://developer.amazon.com/alexa/console/ask) gehen, dann auf den Reiter "Test", und dort den Schalter "Test is enabled for this skill" aktivieren. Danach sollte in der Smartphone-App bei den "installierten Skills" eine "Development"-Sektion auftauchen und "Alexa starte Reisequiz" (o.Ä) erkannt werden.

**Comment by Claraabc** [comment]
Hey cool danke. Bei mir geht das jetzt mit der Alexa App. Aber könntet ihr bitte die aktuellste Version hochladen? Wir können es ja gar nicht testen, wenn ihr uns nur ne alte Version gebt. Wir würden es schon gerne vor Freitag mal richtig ausführlich durchtesten wollen, damit wir auf die Präsentation und die Fragen von unserem Prof vorbereitet sind :)

**Comment by Angiabc** [comment]
Hier die Präsi :)

[Präsi 14.12..pptx](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/files/2680147/Prasi.14.12.pptx)

**Comment by Claraabc** [comment]
Hallo zusammen, wir wünschen euch ein gutes neues Jahr und hoffen ihr hattet schöne Weihnachten! :)
Am Freitag haben wir bei der Präsentation zwei Minuten Zeit, um unseren Skill vorzuführen und dann nochmal eine Minute, um etwas darüber zu sagen. (Unser Prof meinte, dass ihr evtl. von Frau Socher auch noch Vorgaben bekommt...) Jedenfalls haben wir schonmal eine Demo-Version vorbereitet, die unter zwei Minuten dauert. Die darf laut unserem Prof einfach hard-gecodet sein, dass heißt ihr müsstet bitte einen neuen Skill erstellen und in diesen unsere Demo-Version reinkopieren. Die jeweiligen Antworten, die wir dann sagen müssen, merken wir uns einfach. In der Demo wird im 2-Spielermodus gespielt und es wäre super, wenn sich einer von euch bereit erklärt da mitzumachen. (Unser Prof hat gesagt es gibt nen Extrapunkt, wenn ihr auch was sagt 👍) Die eine Minute danach macht dann eine von uns. 
Hier ist mal die Demo-Version:
[Demo.docx](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/files/2729838/Demo.docx)

**Comment by Angiabc** [comment]
Guten Morgen :)
Wir wollten jetzt gerne noch einmal nachhaken, wie es mit der Demo Version ausschaut. Müssen diese morgen testen und heute unserem Prof Bescheid geben, ob wir die hard-gecodete Demo zur Verfügung haben. Wäre super, wenn ihr uns heute noch Bescheid geben könntet, ob die Demo bis morgen fertig gestellt werden kann. 

Unser Prof meinte heute außerdem, dass ihr auch eine kurze Präsentation über das Fachliche halten werdet. Hab ihr da eine Folie oder irgendwas dazu? Falls ja, würden wir die dann in unsere einfügen, sodass wir alles in einem haben.
@Bergmaier @Ruleya @fft5woosh @gsocher

**Comment by Bergmaier** [comment]
Hallo,
eine komplett neue Codebasis für die Demoversion können wir auf die Schnelle nicht erstellen. Wollen wir auch gar nicht wirklich, das gibt bestimmt Minuspunkte wenn wir nicht den "echten" Code am Laufen haben. Was wir allerdings für die Demo machen können:
* Fragen pro Spieler pro Runde von 5 auf 1 setzen
* Verwürfelung der Fragen rausnehmen, dann kommen in jedem Spiel dieselben
* die beiden für die Demo ausgesuchten Fragen ganz zuerst in die Tabelle eintragen
* die "Ortung" auf Berlin hartcoden (sobald das fertig ist... wahrscheinlich noch nicht bis morgen)

Bezüglich einer kurzen Vorstellung der Technik müssen wir uns noch informieren, eine Folie dazu kommt fürchte ich erst kurz vor knapp :-/

Wollen wir uns nochmal treffen, Do oder Fr um die Präsentation abzusprechen und evtl. einzuüben? Gerne gebe ich auch den Peter.

**Comment by Angiabc** [comment]
Okay, ja so hatten wir uns das auch gedacht, guter Vorschlag! 
Ist es denn möglich, eine extra Version davon zu machen, so dass wir auf die ursprüngliche Version trotzdem zugreifen können? Diese brauchen wir nämlich am Freitag auch noch für den Skill-Try out am Freitag.
Schafft ihr das bis morgen?

**Comment by rena611** [comment]
Hallo, 
wollte noch einmal nachfragen, wie es mit der Demo ausschaut? Deinen Vorschlag finden wir gut @Bergmaier 
Bis wann würdet ihr es schaffen die Demo fertig zu stellen? Wir haben jetzt ausgemacht, dass wir uns morgen nachmittag im Vorlesungssaal der Präsi treffen, da könnt ihr dann gerne natürlich auch kommen. Es wäre klasse, wenn die Demo bis zur Generalprobe morgen steht?!
Die Demo wäre an dieser Stelle auch erst einmal wichtiger als die Folie eurer Präsentation, die könnt ihr dann auch gerne erst kurzfristig erstellen. Wir würden die Demo gerne einüben und morgen im Vorlesungssaal testen.

**Comment by Ruleya** [comment]
Wir drei könnten ab 17:00 (Do)
die Demo haben wir dann schon fertig. Passt das? 

btw - sollen die Extra-Infos nach jeder beantworteten Frage kommen wie in der Demo, oder nur nach richtigen Antworten?

**Comment by rena611** [comment]
Okay danke. 17 Uhr geht morgen leider nicht bei uns. Wir werden uns morgen wahrscheinlich nur kurz treffen, um unsere Präsi zu besprechen. Der Raum, in dem Freitag präsentiert wird, ist morgen leider auch fast den ganzen Tag besetzt.
Genau, bitte so wie in der Demo übernehmen, das war genau auf die Angabe von 2 Minuten abgestimmt.

**Comment by Bergmaier** [comment]
Hallo, die Demo funktioniert jetzt. Gestartet wird sie mit "starte ontoury mit demo".

Wenn ihr morgen keine Zeit habt, wollen wir uns am Freitag noch treffen?

**Comment by Claraabc** [comment]
Hey danke für die Demo 👍 Haben sie durchgespielt und passt super für unsere zwei Minuten Vorgabe. Leider sagt Alexa wieder "du hast eins Punkte", das Problem hatten wir ja schonmal... Könntet ihr das bitte nochmal ausbessern? Und die Zusatzinfo sollte auch nach der falschen Antwort kommen. 
Tut uns wirklich Leid, dass wir so Stress deswegen machen, aber unser Prof ist echt voll am durchdrehen. Hat auch heute Vormittag schon wieder in Facebook gepostet warum noch nicht alle Präsentationen online sind... Wir wissen, dass die Socher das um einiges lockerer sieht und das Problem einfach darin besteht, dass unsere Profs es nicht schaffen sich abzusprechen. Hoffentlich versteht ihr das, es wäre wirklich sehr wichtig für uns dass die Demo perfekt ist 😞
Am Freitag müssen wir ab 11:30 anwesend sein (ihr müsst ja dann nur für die zweite Hälfte kommen). Deswegen würde es am Freitag mit einem Treffen nur klappen, wenn ihr um 11:15 da sein könnt. Wir denken aber, dass es mit der Präsi eh keine Probleme geben wird ;) Habt ihr drangedacht die Frau Socher und unseren Prof mit der E-Mail zur Demo hinzuzufügen? Die Demos sollen ja alle über den Echo von Frau Socher laufen. Auch hier kam heute schon ein Facebook-post, dass er noch nicht alle hat... 🙄

**Comment by Bergmaier** [comment]
Hallo, ich versuche schon vor 11:30 da zu sein da mich die anderen Präsentationen auch interessieren :-) Können wir uns auch schon ab 10:00 treffen oder habt ihr erst ab 11:15 Zeit?
Habt ihr schon eine vorläufige Präsentation, wie ist das Design umgesetzt? Müssen wir unsere Folien von der Gestaltung her abstimmen? Könnt ihr uns einen hübschen Hintergrund aussuchen, auf den wir dann heut abend oder morgen früh noch ein oder zwei Bildchen klatschen?

Die Aussprache machen wir noch (Liste aus #39), ich habe sogar #54 bereits in Arbeit - probiert mal "C, schwangere Auster" als Antwort.

**Comment by Angiabc** [comment]
Wir habe leider bis 11:15 Vorlesung und können daher nicht früher..
Hier noch ein Layout, dass ihr verwenden könnt, wenn ihr wollt :)
[Präsentation 11.1.19.pptx](https://github.com/sweIhm-ws2018-19/skillproject-fr-33/files/2745934/Prasentation.11.1.19.pptx)
Unsere Slides habe ich grade  im anderen Post hochgeladen.

Danke  und bis morgen :)

**Comment by Angiabc** [comment]
Noch mal kurze Nachfrage, weil unser Prof gerade geschrieben hat, dass er keinen Zugriff auf unseren Skill hat: Habt ihr ihn und die Frau Socher hinzugefügt?

**Comment by Bergmaier** [comment]
Ja, haben wir beide. amazon.ralpherik@gmail.com stimmt doch, oder? Und er weiß auch dass der Invokation Name "ontoury" ist?

**Comment by Angiabc** [comment]
Okay optimal! Ja müsste passen... ist er auch als Entwickler drinnen?

**Comment by Bergmaier** [comment]
[I review, you review, we all review](http://www.commitstrip.com/en/2019/01/16/i-review-you-review-we-all-review/):
![commitstrip.com](https://www.commitstrip.com/wp-content/uploads/2019/01/Strip-Daily-meeting-english650-finalV2.jpg)
